create table pedido (
status tinyint not null check (status between 0 and 3),
sub_total numeric(38,2) not null,
taxa_frete numeric(38,2) not null,
valor_total numeric(38,2) not null,
data_cancelamento timestamp(6),
data_confirmacao timestamp(6),
data_criacao timestamp(6) not null,
data_entrega timestamp(6),
endereco_cidade_id bigint,
forma_pagamento_id bigint not null,
id bigint generated by default as identity,
restaurante_id bigint not null,
usuario_id bigint not null,
endereco_bairro varchar(255),
endereco_cep varchar(255),
endereco_complemento varchar(255),
endereco_logradouro varchar(255),
endereco_numero varchar(255),

primary key (id));

create table item_pedido (
preco_total numeric(38,2),
preco_unitario numeric(38,2),
quantidade integer,
id bigint generated by default as identity,
pedido_id bigint not null,
produto_id bigint not null,
observacoes varchar(255),

primary key (id));


alter table if exists item_pedido add constraint FK60ym08cfoysa17wrn1swyiuda foreign key (pedido_id) references pedido;
alter table if exists item_pedido add constraint FKtk55mn6d6bvl5h0no5uagi3sf foreign key (produto_id) references produto;
alter table if exists pedido add constraint FKk987vfg9cpgx7qxj3166fdqig foreign key (endereco_cidade_id) references cidade;
alter table if exists pedido add constraint FKqaa411xsl0xu4tkvt1wpccd3b foreign key (forma_pagamento_id) references forma_pagamento;
alter table if exists pedido add constraint FK3eud5cqmgsnltyk704hu3qj71 foreign key (restaurante_id) references restaurante;
alter table if exists pedido add constraint FK6uxomgomm93vg965o8brugt00 foreign key (usuario_id) references usuario;

SET TIME ZONE 'UTC';
